version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: cloud_aws_docker
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app:
    build: .
    container_name: cloud_aws_app
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE:-prod}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cloud_aws_docker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      JWT_SECRET: your-secret-key-here
      JWT_EXPIRATION_MS: 86400000
      JAVA_OPTS: >-
        -Xms256m -Xmx512m
        -Dspring.profiles.active=${PROFILE:-prod}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
