
server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: my-application
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/mydbCloud?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 12Rose#2323
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    require-ssl: false
    headers:
      frame-options: DENY
      xss-protection: 1; mode=block
      content-security-policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';
      referrer-policy: no-referrer
      feature-policy: geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none'

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.yourpackage: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

# File upload configuration
file:
  upload-dir: ${user.home}/app/uploads
  max-file-size: 10MB
  max-request-size: 10MB
  enable-uploads: true

app:
  api:
    version: v1
  cors:
    allowed-origins: "*"
  jwt:
    secret: YvM3wrUKZ98TTgDEQakbOZyERLmfSTNmtFeUG8YMXv/VszKUC6N6dUcp7u8OarYZ
    expiration-ms: 86400000  # 24 hours

# JWT Configuration (for backward compatibility)
jwt:
  secret: ${app.jwt.secret}
  expiration-ms: ${app.jwt.expiration-ms}

security:
  auth:
    whitelist:
      - /api/v1/auth/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /webjars/**
      - /actuator/health

  jwt:
    header: Authorization
    prefix: Bearer
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000